### ISSUE TITLE
Block elements inside of anchor tags

### ISSUE THREAD

**Issue by TheArbalist** [Plailect/Guide_3DS#1514]
On some pages, there are lists containing links to certain scripts and/or files where the links are shown inside code boxes.
This can be confusing, as it is inconsistent with all other linked files.

Additionally, placing block elements (div, code) inside of an anchor tag is not supported in some browsers.
This causes issues for some people, as I've seen on the Discord Server, where people are unable to click links for the GM9 scripts in the final section of the guide.

I suggest formatting the links in question like so: https://i.imgur.com/M8FtmFM.png
This *should* remedy the issue with users being unable to click them.

**Comment by Plailect** [comment]
The HTML is not manually constructed. This site is built using Jekyll, with the page contents being written in Markdown. You can find these contents [here](https://github.com/Plailect/Guide_3DS/tree/master/_pages/en_US). 

That being said, I will look into this bug.

**Comment by Plailect** [comment]
Due to the way the markdown is parsed, I don't see this as being possible since technically a link should not be able to be created within a code element. I'll most likely just remove the code element entirely if I cannot think of a better solution (though this only affects HTML4.1 browsers as HTML5 supports block level elements within anchors).
