### ISSUE TITLE
seedminer guide does not cover JPN consoles

### ISSUE THREAD

**Issue by lorilith** [Plailect/Guide_3DS#1588]
seedminer will fail with the free JPN title due to the patches installing sudoku USA region to it. there are additional steps for launching the, now, cross-region dsiware through squirrelboot

steps covered here: https://gbatemp.net/threads/steelminer-jpn-free-cfw-us-eu-jp-free-homebrew.506166/

**Comment by Plailect** [comment]
Oh I had misunderstood the previous issue. I see now that it was attempting to say that the free JPN title should be used with the steelminer instructions. I will fix that.

**Comment by zoogie** [comment]
The steelminer instructions aren't quite enough, even though it's part of the free JPN cfw process.

This is a good, working overview of the steps needed:
https://gbatemp.net/threads/steelminer-jpn-free-cfw-us-eu-jp-free-homebrew.506166/
(the second part, "Instructions (free cfw for Japan ONLY - and firmware 11.8.0-41J ONLY)")

**Comment by zoogie** [comment]
It's important to read my previous post, but this is brief summary of differences of the free cfw process:

As you know, there is a free JPN dsiware called Daily Health Notebook. It can be injected but there are no JPN dsiwarehax titles available that would "fit" so we have to use US sudoku. The problem with US sudoku is that because it is out-of-region, we have to use homebrew (steelhax) to launch the title with NS_rebootToTitle .(squirrelboot.3dsx).

**Comment by Plailect** [comment]
Yep, I read over those instructions earlier today and understand now what the previous post was trying to say. I will fix this shortly.

**Comment by Plailect** [comment]
Is the required game (and version?) for steelhax even still available?

**Comment by Plailect** [comment]
Is the required game (and version?) for steelhax even still available?

**Comment by zoogie** [comment]
Yes, it has an update, but it's not mandatory.

**Comment by zacchi4k** [comment]
Being the only free compatible DSiWare, wouldn't it be better to link to zoogie's guide instead of removing the game completely while you address it?
